version: '3.7'

services:

  alcove-backup:
    build:
      context: .
      dockerfile: DockerfileBackup
    container_name: alcove-backup

  alcove-dev:
    build:
      context: .
      dockerfile: DockerfileDev
    container_name: alcove-dev




