version: '3.7'

services:

  alcove-backup:
    build:
      context: .
      dockerfile: DockerfileBackup
    container_name: alcove-backup

  alcove-dev:
    build:
      context: .
      dockerfile: DockerfileDev
    environment:
        - NODE_ENV="development"
    #ports:
    #  - "127.0.0.1:443:3000"
    volumes:
        - type: bind
          source: ../
          target: /opt/alcove/
        - type: volume
          source: node_modules
          target: /opt/alcove/node_modules
    container_name: alcove-dev

volumes:
    node_modules:
      name: alcove_node_modules
    config:
      name: alcove_config
